site_name: 'Visual High Throughput Pipeline (VHTP)'
theme:
  name: null
  custom_dir: 'cinder'
  logo: eeg_htpCalcPower/Pictures/logo.svg
nav:
  - Overview: overview.md
  - Table of Contents: index.md